exec expand("source <sfile>:h/packages.vim")
exec expand("source <sfile>:h/key-binding.vim") 
exec expand("source <sfile>:h/user-options.vim")
exec expand("source <sfile>:h/user-commands.vim")
exec expand("source <sfile>:h/status-line.vim")
exec expand("source <sfile>:h/appearance.vim")
