
# general setups
set-option global tabstop 4
add-highlighter global/ number-lines -relative -hlcursor 


# packages
source "~/.local/share/plug-kak/plug.kak/rc/plug.kak"
set-option global plug_install_dir %sh{ echo "$HOME/.local/share/plug-kak" }

plug "andreyorst/plug.kak" noload

plug "ul/kak-lsp" do %{
    cargo build --release --locked
    ln -sf $kak_opt_plug_install_dir/kak-lsp/target/release/kak-lsp ~/.cargo/bin/
} branch "master" tag "v7.0.0" config %{
    source "%val{config}/lsp.kak"
}

plug "delapouite/kakoune-livedown"

plug "guest0x0/coqoune" subset %{
# plug "coqoune" load-path "~/Projects/coq/coqoune" subset %{
    coqoune.kak
} config %{
    source "%val{config}/coq.kak"
}



# custom commands concerning x11
source "%val{config}/x11.kak"

# key maps
source "%val{config}/keymap.kak"

# custom hooks for switch input method through fcitx
source "%val{config}/fcitx.kak"

# colors
source "%val{config}/colors.kak"

# filetype specific plugins
source "%val{config}/ocp-indent.kak"
