
# general setups
set-option global tabstop 4
add-highlighter global/ number-lines -relative -hlcursor 

# lsp
evaluate-commands %sh{ kak-lsp --kakoune -s $kak_session }
hook global WinSetOption filetype=(rust|ocaml) %{
   lsp-enable-window
}

set global lsp_hover_anchor true

define-command lsp-reload-window \
  -params 0 \
  %{ lsp-disable-window; lsp-enable-window }


# custom commands concerning x11
source "%val{config}/x11.kak"

# key maps
source "%val{config}/keymap.kak"

# custom hooks for switch input method through fcitx
source "%val{config}/fcitx.kak"

# colors
source "%val{config}/colors.kak"

# filetype specific plugins
source "%val{config}/ocp-indent.kak"
