

# lsp
evaluate-commands %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|ocaml) %{
    lsp-enable-window
}

set global lsp_hover_anchor true



# custom commands 
define-command -params 1 \
  -file-completion \
  -docstring "open and edit a file in a new window" \
  tabe %{
      evaluate-commands %sh{ 
        setsid -f new-terminal --no-popup --exec kak -c $kak_session $1 < /dev/null > /dev/null 2>&1 &
  }}


# key maps
source "%val{config}/keymap.kak"

# custom scripts
source "%val{config}/fcitx.kak"
