#!/bin/bash

while [ 1 ]; do
  read -p "Are you sure you want to quit i3? [y/n]"
  if [ $REPLY = "y" -o $REPLY = 'yes' ]; then
    i3-msg 'exit'
    exit 0
  elif [ $REPLY = 'n' -o $REPLY = 'no' ]; then
    exit 0
  else
    echo "Don't know what you mean."
  fi;
done

