#!/usr/bin/env zsh

bar_name='bar'$1
# Terminate already running bar instances
ps -ef \
    | grep $bar_name \
    | awk '{ if ($8 != "grep") { system("kill "$2) } }'

# Wait until the processes have been shut down
# while pgrep -u $UID -x polybar >/dev/null; do sleep 1; end

polybar $bar_name -c <(~/.config/polybar/config.gen.zsh) || exit 0
