#!/usr/bin/env zsh

BG_SET=$1
BG_COUNT=$(ls $IMAGES_PATH/BG/$BG_SET | wc -w)
feh --no-fehbg --bg-scale \
    $IMAGES_PATH/BG/$BG_SET/$(ls $IMAGES_PATH/BG/$BG_SET | grep $((RANDOM%BG_COUNT + 1))) \
    $IMAGES_PATH/BG/$BG_SET/$(ls $IMAGES_PATH/BG/$BG_SET | grep $((RANDOM%BG_COUNT + 1)))
