#!/bin/zsh


ZSH_HIGHLIGHT_RIGHLIGHTERS=(main, bracket, paren, cursor)

typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]=fg=#feeeed
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=#f36c21
ZSH_HIGHLIGHT_STYLES[builtin]=fg=#f58220
ZSH_HIGHLIGHT_STYLES[alias]=fg=#fcaf17
ZSH_HIGHLIGHT_STYLES[command]=fg=#ffffff
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=#ff0000
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=#00d700
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=#00d700
# ZSH_HIGHLIGHT_STYLES[command-substitution]=fg=none
# ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]=fg=#ffe600
# ZSH_HIGHLIGHT_STYLES[command-substitution-unquoted]=fg=none
# ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]=fg=#ffe600
# ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]=fg=#ffe600
# ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]=fg=#ffe600
