#!/bin/zsh

if [[ -o NO_RCS ]]; then
    source "$HOM/.zshenv"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install
#
# The following lines were added by compinstall
zstyle :compinstall filename '/home/usr0/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
#
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search 
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search 

# load plugins
source "$ZSH_PLUG_PATH/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$ZSH_PLUG_PATH/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# z.lua
eval "$(lua $ZSH_PLUG_PATH/z.lua/z.lua --init zsh enhanced)"
alias zb='z -b'
alias zc='z -c $PWD'

# alias
# 'sudo kak', with config properly loaded
alias skak="sudo env KAKOUNE_CONFIG_DIR=$HOME/.config/kak kak"
# emacs client
alias emc="emacsclient -a '' -t"
alias ls='ls --color=auto'


# prompt
source "$ZSH_DOT_PATH/prompt"
export PROMPT_PATH_MAX_LEN=10

# colors
source "$ZSH_DOT_PATH/key-bindings"
source "$ZSH_DOT_PATH/highlights"

# options
setopt PROMPT_SUBST
unsetopt correct_all
unsetopt correct
DISABLE_CORRECTION='true'

setopt inc_append_history

fpath=("$MY_ZSH_DOT_PATH/functions" $fpath)
export PATH="$HOME/.cargo/bin":"$HOME/.linuxbrew/bin":"$SCRIPTS_PATH:$PATH"

# eval $(opam env)

# opam configuration
test -r /home/guest0/.opam/opam-init/init.zsh && . /home/guest0/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
