#!/bin/zsh

if [[ -o NO_RCS ]]; then
    source "$HOME/.zshenv"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install
#
# The following lines were added by compinstall
zstyle :compinstall filename '/home/usr0/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
#
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search 
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search 

# load plugins
if [ -d "$ZSH_PLUG_PATH" ]; then
    source "$ZSH_PLUG_PATH/zsh-autosuggestions/zsh-autosuggestions.zsh"
    source "$ZSH_PLUG_PATH/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# z.lua
if [ -d "$ZSH_PLUG_PATH" ]; then
    eval "$(lua $ZSH_PLUG_PATH/z.lua/z.lua --init zsh enhanced)"
elif z --help >/dev/null; then
    eval "$(z --init zsh enhanced)"
fi
if z -h >/dev/null; then
    alias zb='z -b'
    alias zc='z -c $PWD'
fi

# alias
# 'sudo kak', with config properly loaded
alias skak="sudo env HOME=$HOME kak"
# emacs client
alias emc="emacsclient -a '' -t"
alias ls='ls --color=auto'


# prompt
source "$ZSH_DOT_PATH/prompt.zsh"
export PROMPT_PATH_MAX_LEN=10

# colors
source "$ZSH_DOT_PATH/key-bindings.zsh"
source "$ZSH_DOT_PATH/highlights.zsh"

# options
setopt PROMPT_SUBST
unsetopt correct_all
unsetopt correct
DISABLE_CORRECTION='true'

setopt inc_append_history

fpath=("$MY_ZSH_DOT_PATH/functions" $fpath)
export PATH="$HOME/.luarocks/bin":"$HOME/.cargo/bin":"$HOME/.linuxbrew/bin":"$SCRIPTS_PATH:$PATH"

# eval $(opam env)

# opam configuration
test -r /home/guest0/.opam/opam-init/init.zsh && . /home/guest0/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
