;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        sov-backward-char/expand
        sov-backward-char/move
        sov-backward-word/expand
        sov-backward-word/select
        sov-copy-region
        sov-forward-char/expand
        sov-forward-char/move
        sov-forward-word/expand
        sov-forward-word/select
        sov-kill
        sov-line/expand
        sov-line/select
        sov-next-line/expand
        sov-next-line/move
        sov-previous-line/expand
        sov-previous-line/move
        ))

(setq mc/cmds-to-run-once
      '(
        mc/mark-all-in-region
        undefined
        ))
